name: Document Service Client NuGet CI

env:
  PROJPATH: './src/Kmd.Logic.DocumentService.Client'
  DOTNET_VERSION: '3.1.301'

on:
  push:
    branches: [ master, dev ]
    paths: 
    - 'src/**'
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HHmm

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore '${{ env.PROJPATH }}/Kmd.Logic.DocumentService.Client.csproj'

    - name: Build - PreRelease
      run: dotnet build '${{ env.PROJPATH }}/Kmd.Logic.DocumentService.Client.csproj' --configuration Debug --no-restore -p:VersionSuffix=dev-${{ steps.current-time.outputs.formattedTime }}
      if: GITHUB.REF != 'refs/heads/master'
    - name: Build - Release
      run: dotnet build '${{ env.PROJPATH }}/Kmd.Logic.DocumentService.Client.csproj' --configuration Release --no-restore
      if: GITHUB.REF == 'refs/heads/master'

    - name: Pack - PreRelease
      run: dotnet pack '${{ env.PROJPATH }}/Kmd.Logic.DocumentService.Client.csproj' --output ${{ env.PROJPATH }}/nupkgs --no-restore -p:VersionSuffix=dev-${{ steps.current-time.outputs.formattedTime }}
      if: GITHUB.REF != 'refs/heads/master'
    - name: Pack - Release
      run: dotnet pack '${{ env.PROJPATH }}/Kmd.Logic.DocumentService.Client.csproj' --output ${{ env.PROJPATH }}/nupkgs --no-restore
      if: GITHUB.REF == 'refs/heads/master'
